### ISSUE TITLE
Sigpanic when i resize the window

### ISSUE THREAD

**Issue by Nurza** [bobappleyard/readline#17]
Hello, i found a bug:

Take your example script, make it as a main package.

```
package main

import (
	"fmt"
	"github.com/bobappleyard/readline"
	"os"
	"os/signal"
	"syscall"
	"time"
)

func main() {
	time.Sleep(time.Minute)
	sigint := make(chan os.Signal, 1)
	signal.Notify(sigint, syscall.SIGINT)
	readline.CatchSigint = false
	var line string
	var err error
	done := make(chan struct{})
	go func() {
		line, err = readline.String("> ")
		close(done)
	}()
	select {
	case <-sigint:
		fmt.Println("\nInterrupted")
		// Restore terminal attributes
		readline.Cleanup()
		// Note that we still have a goroutine reading from Stdin that
		// will terminate when we exit.
		os.Exit(1)
	case <-done:
		fmt.Printf("Read line %s, error %v\n", line, err)
	}
}

```

Run the program. When you resize the console: sigpanic

```
fatal error: unexpected signal during runtime execution

[signal 0xb code=0x1 addr=0x0 pc=0x7fc8d9370070]

runtime stack:
runtime.gothrow(0x54e470, 0x2a)
	/usr/local/go/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:14 +0x5e

goroutine 6 [syscall, locked to thread]:
runtime.cgocall_errno(0x401c60, 0xc208018710, 0xc200000000)
	/usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc2080186f0 sp=0xc2080186c8
github.com/bobappleyard/readline._Cfunc_rl_resize_terminal()
	/home/manager/gopath/src/github.com/bobappleyard/readline/:116 +0x45 fp=0xc208018710 sp=0xc2080186f0
github.com/bobappleyard/readline.handleSignals()
	/home/manager/gopath/src/github.com/bobappleyard/readline/readline.go:321 +0x2be fp=0xc2080187e0 sp=0xc208018710
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080187e8 sp=0xc2080187e0
created by github.com/bobappleyard/readline.init·1
	/home/manager/gopath/src/github.com/bobappleyard/readline/readline.go:333 +0x25

goroutine 1 [sleep]:
main.main()
	/home/manager/readline/main.go:13 +0x38

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
exit status 2
```

I am using Go1.4.1 on a Debian Linux Jessie.
I have tested the bug with Gnome Terminal and Terminator

**Comment by Nurza** [comment]
Actually, the program panic when i use your lib until i call the function readline.String("")

**Comment by bobappleyard** [comment]
Yeah I've no idea what that's doing.

Looking at the blame for the file, it looks like it was introduced to show how to use Cleanup(). But that gets called automatically now so it's probably pointless keeping the file around.

**Comment by bobappleyard** [comment]
Just ignoring all the stuff about signals and what have you handles resizing fine at my end (Go 1.4.1 Ubuntu 14.04 on Gnome Terminal)

i.e.

    package main

    import (
        "fmt"
        "github.com/bobappleyard/readline"
    )

    func main() {
        var line string
        var err error
        line, err = readline.String("> ")
        fmt.Println(line, err)
    }
